#!/bin/bash
#
# nmcli-cli-autoconnect-set

NAME=$1
ON_OFF=${2}

if [[ -z "${ON_OFF}" ]]; then
    cat << _EOF_
Usage:

    $0 NAME ON|OFF

    EXAMPLES

        $0 eno1 off
        $0 bond1 on

_EOF_
    exit 1
fi

# Check interface
nmcli connection show "${NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${NAME} not found."
    exit 1
fi

# auutoconnect
echo nmcli connection modify \"${NAME}\" connection.autoconnect \"${ON_OFF}\"
# nmcli connection modify "${NAME}" connection.autoconnect "${ON_OFF}"

