#!/bin/bash
#
# nmcli-cli-bridge-delete

ECHO_OR_EXECUTE="echo"

usage() {
    cat << _EOF_
Usage:

    $0 [-n] [-x] BRIDGE_NAME

    Options:
        -n No interface check (Default: check interface)
        -x Run command (Default: echo only)

    Examples:
        $0 br1

_EOF_
}

check() {
    local BRDIGE_IF_NAME=${1:-}

    # Check bridge interface
    nmcli connection show "${BRDIGE_IF_NAME}" > /dev/null 2>&1
    RET=$?
    if [[ ${RET} -ne 0 ]]; then
       echo "Error: Target bridge interface \"${BRDIGE_IF_NAME}\" not found."
       exit 1
   fi
}

echo_or_execute() {
    if [[ -z "${ECHO_OR_EXECUTE}" ]]; then
        echo "Applying: ${@}"
        eval ${@}
    else
        ${ECHO_OR_EXECUTE} ${@}
    fi
}

bridge_delete() {
    local BRIDGE_NAME=${1:-}

    # Find slave interfaces
    SLAVE_LIST=$(grep "^BRIDGE=${BRIDGE_NAME}$" /etc/sysconfig/network-scripts/ifcfg-* | cut -d':' -f 1 | sed 's|.*/ifcfg-||g')

    # Delete slave interfaces
    for i in ${SLAVE_LIST}
    do
        echo_or_execute nmcli connection modify \"${i}\" connection.master \"\" connection.slave-type \"\"
    done

    # Delete bridge interface
    echo nmcli connection delete \"${BRIDGE_NAME}\"
}

# Main
main() {
    local NO_CHECK="no"
    while getopts nxh OPT; do
        case "${OPT}" in
            "n" )
                NO_CHECK="yes" ;;
            "x" )
                ECHO_OR_EXECUTE="" ;;
            "h" )
                usage
                exit 0
                ;;
            * )
                usage
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))

    [[ $# -le 0 ]] && usage && exit 1

    if [[ "${NO_CHECK}" = "no" ]]; then
        check "${@}"
    fi

    if [[ "${ECHO_OR_EXECUTE}" = "echo" ]]; then
        echo "# ${ECHO_OR_EXECUTE} only."
    fi

    bridge_delete "${@}"
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"

