#!/bin/bash
#
# nmcli-cli-vlan-add

VLAN_IF_NAME=$1
IF_NAME=$2
VLAN_ID=$3

if [[ -z "${VLAN_ID}" ]]; then
    cat << _EOF_
Usage:

    $0 VLAN_IF_NAME IF_NAME VLAN_ID

    EXAMPLES

        $0 eno1.100 eno1 100
        $0 vlan.100 bond1 100

_EOF_
    exit 1
fi

# Check new vlan interface
nmcli connection show "${VLAN_IF_NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -eq 0 ]]; then
    echo "Error: Interface ${VLAN_IF_NAME} already exists."
    exit 1
fi

# Check interface
nmcli connection show "${IF_NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${IF_NAME} not found."
    exit 1
fi

# Add vlan interface
echo nmcli connection add type vlan ipv4.method disabled ipv6.method ignore con-name \"${VLAN_IF_NAME}\" ifname \"${VLAN_IF_NAME}\" dev \"${IF_NAME}\" id ${VLAN_ID}
# nmcli connection add type vlan ipv4.method disabled ipv6.method ignore con-name "${VLAN_IF_NAME}" ifname "${VLAN_IF_NAME}" dev "${IF_NAME}" id ${VLAN_ID}

