#!/bin/bash
#
# nmcli-cli-slave-list

usage() {
    cat << _EOF_
Usage:
    $0 IF_NAME

    Examples:
        $0 bond1
        $0 br1

_EOF_
}

slave_list() {
    local IF_NAME=$1

    # Bond: Find slave interfaces
    SLAVE_LIST=$(grep "^MASTER=${IF_NAME}$" /etc/sysconfig/network-scripts/ifcfg-* | cut -d':' -f 1 | egrep -o "bond-slave.*")

    # Print slave interfaces
    for i in ${SLAVE_LIST}
    do
        echo "${i}"
    done

    # Bridge: Find slave interfaces
    SLAVE_LIST=$(grep "^BRIDGE=${IF_NAME}$" /etc/sysconfig/network-scripts/ifcfg-* | cut -d':' -f 1 | sed 's|.*/ifcfg-||g')

    # Print slave interfaces
    for i in ${SLAVE_LIST}
    do
        echo "${i}"
    done
}

# Main
main() {
    [[ $# -le 0 ]] && usage && exit 1

    slave_list "${@}"
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"

