#!/bin/bash
#
# nmcli-cli-autoconnect-list
#
# Copyright (c) 2019 Jun Futagawa (jfut)
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

usage() {
    cat << _EOF_
Usage:

    $0 all
    $0 yes|no or on|off

    Examples:
        $0 all
        $0 yes

_EOF_
}

autoconnect_list() {
    ON_OFF=${1:-}

    if [[ "${ON_OFF}" == "all" ]]; then
        ON_OFF="all"
    elif [[ "${ON_OFF}" == "on" ]] || [[ "${ON_OFF}" == "yes" ]]; then
        ON_OFF="yes"
    elif [[ "${ON_OFF}" == "off" ]] || [[ "${ON_OFF}" == "no" ]]; then
        ON_OFF="no"
    else
        echo "Error: option \"${ON_OFF}\" is invalid."
        exit 1
    fi

    # list
    LIST=$(nmcli connection | awk '{ print $1 }' | grep -v "^NAME$")
    for INTERFACE in ${LIST}
    do
        STATUS_LINE=$(nmcli connection show "${INTERFACE}" | grep connection.autoconnect:)
        STATUS=$(echo "${STATUS_LINE}" | awk '{ print $2 }')
        if [[ "${ON_OFF}" == "all" ]] || [[ "${STATUS}" == "${ON_OFF}" ]]; then
            echo "${INTERFACE}"
        fi
    done
}

# Main
main() {
    [[ $# -lt 1 ]] && usage && exit 1

    autoconnect_list "${@}"
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"

