#!/bin/bash
#
# nmcli-cli-vlan-delete

ECHO_OR_EXECUTE="echo"

echo_or_execute() {
    if [[ -z "${ECHO_OR_EXECUTE}" ]]; then
        echo "Applying: ${@}"
        eval ${@}
    else
        ${ECHO_OR_EXECUTE} ${@}
    fi
}

usage() {
    cat << _EOF_
Usage:

    $0 [-n] [-x] VLAN_IF_NAME

    Options:
        -n No interface check (Default: check interface)
        -x Run command (Default: echo only)

    Examples:
        $0 bond1

_EOF_
}

check() {
    local VLAN_IF_NAME=${1:-}

    # Check vlan interface
    nmcli connection show "${VLAN_IF_NAME}" > /dev/null 2>&1
    RET=$?
    if [[ ${RET} -ne 0 ]]; then
        echo "Error: Target vlan interface \"${VLAN_IF_NAME}\" not found."
        exit 1
    fi
}

vlan_delete() {
    local VLAN_IF_NAME=${1:-}

    # Delete vlan interface
    echo_or_execute nmcli connection delete \"${VLAN_IF_NAME}\"
}

# Main
main() {
    local NO_CHECK="no"
    while getopts nxh OPT; do
        case "${OPT}" in
            "n" )
                NO_CHECK="yes" ;;
            "x" )
                ECHO_OR_EXECUTE="" ;;
            "h" )
                usage
                exit 0
                ;;
            * )
                usage
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))

    [[ $# -le 0 ]] && usage && exit 1

    if [[ "${NO_CHECK}" = "no" ]]; then
        check "${@}"
    fi

    if [[ "${ECHO_OR_EXECUTE}" = "echo" ]]; then
        echo "# ${ECHO_OR_EXECUTE} only."
    fi

    vlan_delete "${@}"
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"

