#!/bin/bash
#
# nmcli-tool-bond-add

BOND_IF_NAME=$1
IF_SLAVE1=$2
IF_SLAVE2=$3
BOND_OPTIONS=$4

if [[ -z "${BOND_OPTIONS}" ]]; then
    cat << _EOF_
Usage:

    $0 NEW_BOND_IF_NAME IF_SLAVE1 IF_SLAVE2 BOND_OPTIONS

    EXAMPLES

        $0 bond1 eno1 ens2f0 mode=802.3ad,miimon=100,updelay=500,xmit_hash_policy=layer2+3
        $0 bond1 eno1 ens2f0 mode=active-backup

_EOF_
    exit 1
fi

# Check new bond interface
nmcli connection show "${BOND_IF_NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -eq 0 ]]; then
    echo "Error: Interface ${BOND_IF_NAME} already exists."
    exit 1
fi

# Check interface: Slave 1
nmcli connection show "${IF_SLAVE1}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${IF_SLAVE1} not found."
    exit 1
fi

# Check interface: Slave 2
nmcli connection show "${IF_SLAVE2}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${IF_SLAVE2} not found."
    exit 1
fi

# Bonding
echo nmcli connection add type bond autoconnect yes con-name \"${BOND_IF_NAME}\" ifname \"${BOND_IF_NAME}\"
# nmcli connection add type bond autoconnect yes con-name "${BOND_IF_NAME}" ifname "${BOND_IF_NAME}"

# Slave 1
echo nmcli connection add type bond-slave autoconnect yes ifname \"${IF_SLAVE1}\" master \"${BOND_IF_NAME}\"
# nmcli connection add type bond-slave autoconnect yes ifname "${IF_SLAVE1}" master "${BOND_IF_NAME}"

# Slave 2
echo nmcli connection add type bond-slave autoconnect yes ifname \"${IF_SLAVE2}\" master \"${BOND_IF_NAME}\"
# nmcli connection add type bond-slave autoconnect yes ifname "${IF_SLAVE2}" master "${BOND_IF_NAME}"

# Bonding Options
echo nmcli connection modify \"${BOND_IF_NAME}\" bond.options \"${BOND_OPTIONS}\"
# nmcli connection modify "${BOND_IF_NAME}" bond.options "${BOND_OPTIONS}"

# autoconnect no: Slave 1
echo nmcli connection modify \"${IF_SLAVE1}\" connection.autoconnect no
# nmcli connection modify "${IF_SLAVE1}" connection.autoconnect no

# autoconnect no: Slave 2
echo nmcli connection modify \"${IF_SLAVE2}\" connection.autoconnect no
# nmcli connection modify "${IF_SLAVE2}" connection.autoconnect no

