#!/bin/bash
#
# nmcli-cli-slave-list
#
# Copyright (c) 2019-2026 Jun Futagawa (jfut)
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

VERSION="1.2.0"

usage() {
    local COMMAND_NAME
    COMMAND_NAME="$(basename "${0}")"

    cat << _EOF_
${COMMAND_NAME} ${VERSION}

Usage:

    ${COMMAND_NAME} IF_NAME

    Examples:
        ${COMMAND_NAME} bond1
        ${COMMAND_NAME} vlan.100
        ${COMMAND_NAME} br1
_EOF_
}

slave_list() {
    local IF_NAME=${1:-}
    local i

    # Find lower interfaces
    TARGET="/sys/class/net/${IF_NAME}/"
    if [[ -e "${TARGET}" ]]; then
        for i in "${TARGET}"/lower_*; do
            [[ -e "${i}" ]] || continue
            echo "${i##*/lower_}"
        done
    fi
}

# Main
main() {
    [[ $# -lt 1 ]] && usage && exit 1

    slave_list "${@}"
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && main "$@"
