#!/bin/bash
#
# nmcli-tool-ip-copy

SRC_NAME=$1
DEST_NAME=$2

if [[ -z "${DEST_NAME}" ]]; then
    cat << _EOF_
Usage:

    $0 SRC_NAME DEST_NAME

    EXAMPLES

        $0 eno1 bond1
        $0 bond1 br1

_EOF_
    exit 1
fi

# Check interface: src
nmcli connection show "${SRC_NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${SRC_NAME} not found."
    exit 1
fi

# Check interface: dest
nmcli connection show "${DEST_NAME}" > /dev/null 2>&1
RET=$?
if [[ ${RET} -ne 0 ]]; then
    echo "Error: Interface ${DEST_NAME} not found."
    exit 1
fi

# IP
SRC_IP_SUBNET=$(nmcli connection show "${SRC_NAME}" | grep "^ipv4.addresses:" | awk -e '{ print $2 }' | tr -d '-')
echo nmcli connection modify \"${DEST_NAME}\" ipv4.addresses \"${SRC_IP_SUBNET}\"

# Method
SRC_METHOD=$(nmcli connection show "${SRC_NAME}" | grep "^ipv4.method:" | awk -e '{ print $2 }' | tr -d '-')
echo nmcli connection modify \"${DEST_NAME}\" ipv4.method \"${SRC_METHOD}\"

# DNS
SRC_DNS=$(nmcli connection show "${SRC_NAME}" | grep "^ipv4.dns:" | awk -e '{ print $2 }' | tr -d '-')
echo nmcli connection modify \"${DEST_NAME}\" ipv4.dns \"${SRC_DNS}\"

# Gateway
SRC_GATEWAY=$(nmcli connection show "${SRC_NAME}" | grep "^ipv4.gateway:" | awk -e '{ print $2 }' | tr -d '-')
echo nmcli connection modify \"${DEST_NAME}\" ipv4.gateway \"${SRC_GATEWAY}\"

